server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmacy_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: medicine-stock-events
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  output:
    ansi:
      enabled: always

management:
  endpoints:
    web:
      exposure:
        include: refresh